@OllamaProject_HostAddress = https://localhost:7165
@OllamaProject_HostAddress = http://localhost:5239

GET {{OllamaProject_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{OllamaProject_HostAddress}}/weatherforecast

###

POST {{OllamaProject_HostAddress}}/api/email
Content-Type: application/json

{
  //EmailDTO
}

###
