// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OllamaProject.Data;

#nullable disable

namespace OllamaProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240517182101_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OllamaProject.Entities.Preguntas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Consulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormularioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
